import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, ArrowLeft, BarChart3, Check, ChevronRight, CircleHelp, Copy, Crown, Gavel, LogIn, LogOut, Pause, Play, RotateCcw, Shield, Sparkles, Trophy, Users, Volume2, VolumeX, Wallet, X, Zap } from 'lucide-react';
import { socket, SERVER_URL } from './lib/socket.js';

const TEAMS = [
  ['CSK','Chennai Super Kings'],['MI','Mumbai Indians'],['RCB','Royal Challengers Bengaluru'],['KKR','Kolkata Knight Riders'],['SRH','Sunrisers Hyderabad'],['RR','Rajasthan Royals'],['DC','Delhi Capitals'],['PBKS','Punjab Kings'],['LSG','Lucknow Super Giants'],['GT','Gujarat Titans']
];
const teamColor = {CSK:'#f4c430',MI:'#39a9ff',RCB:'#ef4444',KKR:'#a855f7',SRH:'#fb923c',RR:'#ec4899',DC:'#60a5fa',PBKS:'#f43f5e',LSG:'#22d3ee',GT:'#94a3b8'};
const money = n => `₹${Number(n || 0).toFixed(2)} Cr`;

const outcomeAudio = { gavel:null, buzzer:null };
function preloadOutcomeAudio(){
  if(typeof window==='undefined') return;
  if(!outcomeAudio.gavel){ outcomeAudio.gavel=new Audio('/audio/gavel-hit.wav'); outcomeAudio.gavel.preload='auto'; outcomeAudio.gavel.load(); }
  if(!outcomeAudio.buzzer){ outcomeAudio.buzzer=new Audio('/audio/unsold-buzzer.wav'); outcomeAudio.buzzer.preload='auto'; outcomeAudio.buzzer.load(); }
}
function playOutcomeSound(kind){
  try{
    preloadOutcomeAudio();
    if(kind==='sold'){
      if('speechSynthesis' in window){ window.speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance('SOLD!'); u.rate=0.82; u.pitch=0.82; u.volume=1; window.speechSynthesis.speak(u); }
      const a=outcomeAudio.gavel; if(a){ a.currentTime=0; a.volume=.82; window.setTimeout(()=>a.play().catch(()=>{}),520); }
    } else if(kind==='unsold'){
      const a=outcomeAudio.buzzer; if(a){ a.currentTime=0; a.volume=.58; a.play().catch(()=>{}); }
    }
  }catch{}
}

function App(){
  const [screen,setScreen] = useState('home');
  const [mode,setMode] = useState('create');
  const [name,setName] = useState('');
  const [teamId,setTeamId] = useState('RCB');
  const [roomCode,setRoomCode] = useState('');
  const [pendingRoomCode,setPendingRoomCode] = useState('');
  const [copied,setCopied] = useState(false);
  const [room,setRoom] = useState(null);
  const [userId,setUserId] = useState(localStorage.getItem('paddleup_user') || '');
  const [error,setError] = useState('');
  const [toast,setToast] = useState('');
  const [remaining,setRemaining] = useState(0);
  const [sound,setSound] = useState(true);
  const [results,setResults] = useState(null);
  const [how,setHow] = useState(false);
  const lastOutcomeRef = useRef('');

  useEffect(()=>{
    preloadOutcomeAudio();
    const onRoom = r => { setRoom(r); if(r.status === 'ENDED') setScreen('results'); else if(r.status === 'LIVE' || r.status === 'PAUSED') setScreen('auction'); else setScreen('lobby'); };
    const onJoined = ({room,userId:id}) => { setUserId(id); localStorage.setItem('paddleup_user',id); localStorage.setItem('paddleup_room',room.code); setRoom(room); setError(''); setScreen(room.status === 'ENDED' ? 'results' : (room.status === 'WAITING' ? 'lobby' : 'auction')); };
    const onTick = ({remaining:r}) => { setRemaining(r); const sec=Math.ceil(r); if(sound && sec<=3 && sec>=1 && sec!==window.__paddleLastSecond){ window.__paddleLastSecond=sec; auctionSound('countdown'); } if(sec>3) window.__paddleLastSecond=null; };
    const onBid = ({teamId:t, amount, bidderName}) => { setToast(`${t} bid ${money(amount)} — ${bidderName}`); auctionSound(sound ? 'bid' : null); };
    const onSold = ({player,team,price}) => { const key=`SOLD:${player?.id}:${team?.short}:${price}`; if(lastOutcomeRef.current!==key){ lastOutcomeRef.current=key; setToast({type:'SOLD', title:'SOLD', text:player.name, detail:`${team.short} · ${money(price)}`}); if(sound) playOutcomeSound('sold'); } setRemaining(0); };
    const onUnsold = ({player}) => { const key=`UNSOLD:${player?.id}`; if(lastOutcomeRef.current!==key){ lastOutcomeRef.current=key; setToast({type:'UNSOLD', title:'UNSOLD', text:player.name, detail:'No successful bid'}); if(sound) playOutcomeSound('unsold'); } setRemaining(0); };
    const onComplete = () => { setRemaining(0); setScreen('results'); };
    const onConnect = () => {
      const savedCode = localStorage.getItem('paddleup_room');
      const savedUser = localStorage.getItem('paddleup_user');
      if (savedCode && savedUser) socket.emit('room:reconnect', { code: savedCode, userId: savedUser, name });
    };
    const onError = ({message}) => { setError(message); setToast(message); };
    const onTransfer = ({name:n}) => setToast(`Host transferred to ${n}`);
    socket.on('connect',onConnect); socket.on('room:update',onRoom); socket.on('room:joined',onJoined); socket.on('auction:tick',onTick); socket.on('auction:new-player',({player})=>{ setToast(`Now on the block: ${player.name}`); }); socket.on('auction:bid',onBid); socket.on('auction:sold',onSold); socket.on('auction:unsold',onUnsold); socket.on('auction:complete',onComplete); socket.on('game:error',onError); socket.on('host:transferred',onTransfer);
    return ()=>{ socket.off('connect',onConnect); socket.off('room:update',onRoom); socket.off('room:joined',onJoined); socket.off('auction:tick',onTick); socket.off('auction:new-player'); socket.off('auction:bid',onBid); socket.off('auction:sold',onSold); socket.off('auction:unsold',onUnsold); socket.off('auction:complete',onComplete); socket.off('game:error',onError); socket.off('host:transferred',onTransfer); };
  },[sound]);
  useEffect(()=>{ if(toast){const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)} },[toast]);
  useEffect(()=>{ if(userId) socket.auth={userId,name}; },[userId,name]);
  useEffect(()=>{ const savedCode=localStorage.getItem('paddleup_room'); const savedUser=localStorage.getItem('paddleup_user'); if(savedCode && savedUser && !socket.connected){ socket.auth={userId:savedUser,name}; socket.connect(); } },[]);

  const create = ()=>{ if(!name.trim()) return setError('Enter your name.'); setError(''); localStorage.removeItem('paddleup_room'); socket.auth={name:name.trim(), userId:''}; if(!socket.connected) socket.connect(); socket.emit('room:create',{name:name.trim(),teamId}); };
  const join = ()=>{ if(!name.trim()) return setError('Enter your name.'); if(!roomCode.trim()) return setError('Enter the room code.'); setError(''); socket.auth={name:name.trim(), userId:''}; if(!socket.connected) socket.connect(); socket.emit('room:join',{code:roomCode.trim(),name:name.trim(),teamId}); };
  const copyLink = async()=>{ if(!room?.code) return; let host=location.hostname; try { if(['localhost','127.0.0.1'].includes(host)){ const r=await fetch(`${SERVER_URL}/api/network`); const data=await r.json(); host=data.lanIp||host; } } catch {} const protocol=location.protocol==='https:'?'https':'http'; const link=`${protocol}://${host}:5173/?room=${room.code}`; try { await navigator.clipboard.writeText(link); setCopied(true); } catch { window.prompt('Copy this room link:', link); setCopied(true); } setToast('Invite link copied'); setTimeout(()=>setCopied(false),2200);};
  const myPlayer = room?.players?.find(p=>p.id===userId);
  const myTeam = myPlayer?.teamId;
  const currentPlayer = room?.currentAuction ? room.playerPool?.find(p=>p.id===room.currentAuction.playerId) : null;
  const myTeamData = myTeam && room ? room.teams[myTeam] : null;
  const isHost = room?.hostId===userId;

  useEffect(()=>{ const code=new URLSearchParams(location.search).get('room'); if(code){ const clean=code.toUpperCase(); setPendingRoomCode(clean); setRoomCode(clean); setScreen('home'); window.history.replaceState({},'',location.pathname); } },[]);

  if(screen==='home') return <><Home pendingRoomCode={pendingRoomCode} onCreate={()=>{setPendingRoomCode('');setMode('create');setScreen('entry')}} onJoin={()=>{setMode('join');if(pendingRoomCode)setRoomCode(pendingRoomCode);setScreen('entry')}} onHow={()=>setHow(true)} />{how&&<HowModal onClose={()=>setHow(false)}/>}</>;
  if(screen==='entry') return <Entry mode={mode} name={name} setName={setName} teamId={teamId} setTeamId={setTeamId} roomCode={roomCode} setRoomCode={setRoomCode} onBack={()=>setScreen('home')} onSubmit={mode==='create'?create:join} error={error} />;
  if(screen==='lobby' && room) return <Lobby room={room} userId={userId} isHost={isHost} copyLink={copyLink} copied={copied} onStart={()=>socket.emit('host:start')} onBack={()=>{localStorage.removeItem('paddleup_room');socket.disconnect();setRoom(null);setScreen('home')}} />;
  if((screen==='auction' || (room?.status==='LIVE'||room?.status==='PAUSED')) && room) return <Auction room={room} userId={userId} myTeam={myTeam} isHost={isHost} remaining={remaining} sound={sound} setSound={setSound} currentPlayer={currentPlayer} myTeamData={myTeamData} toast={toast} />;
  if(screen==='results' && room) return <Results room={room} onAgain={()=>{localStorage.removeItem('paddleup_room');setScreen('home');setRoom(null);setResults(null);socket.disconnect()}} />;
  return <Home pendingRoomCode={pendingRoomCode} onCreate={()=>{setMode('create');setScreen('entry')}} onJoin={()=>{setMode('join');setScreen('entry')}} onHow={()=>setHow(true)} />;
}

function Home({onCreate,onJoin,onHow,pendingRoomCode}){ return <div className="home page-shell"><div className="noise"/><nav className="topbar"><Brand/><button className="icon-btn" onClick={onHow}><CircleHelp size={19}/><span>How to play</span></button></nav><main className="hero"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} className="hero-copy"><div className="eyebrow"><span className="live-dot"/> REAL-TIME IPL AUCTION GAME</div><h1>Build your squad.<br/><span>Rule the auction.</span></h1><p>Bring your friends into a private room, fight over stars, manage ₹120 Cr and build the squad you believe in.</p><div className="hero-actions"><button className="primary big" onClick={onCreate}><Zap size={19}/> Create Room</button><button className="secondary big" onClick={onJoin}><LogIn size={19}/> {pendingRoomCode?`Join ${pendingRoomCode}`:'Join Room'}</button></div>{pendingRoomCode&&<div className="invite-detected"><span className="live-dot"/> INVITE DETECTED <b>{pendingRoomCode}</b><small>Tap Join Room to enter the auction.</small></div>}<div className="mini-stats"><span><Users/> Up to 10 teams</span><span><Gavel/> 10 sec bids</span><span><Wallet/> ₹120 Cr purse</span></div></motion.div><motion.div initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} className="hero-card"><div className="stadium-glow"/><div className="hero-ball">🏏</div><div className="score-line"><span>AUCTION NIGHT</span><b>LIVE</b></div><div className="mock-player"><div className="mock-avatar">VK</div><div><small>CURRENT PLAYER</small><strong>Virat Kohli</strong><span>Batsman · Rating 94</span></div><div className="mock-price">₹15.50 Cr</div></div><div className="mock-timer"><div className="timer-ring"><span>07</span></div><div><small>HIGHEST BID</small><strong>RCB</strong><span>Timer resets after every bid</span></div></div></motion.div></main><footer><span>© PADDLE UP</span><span>Fast. Competitive. Built for friends.</span></footer></div> }

function HowModal({onClose}){ return <div className="modal-backdrop" onClick={onClose}><div className="how-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">HOW TO PLAY</div><h2>Build your squad. Rule the auction.</h2><ol><li>Create or join a private room.</li><li>Choose one available IPL team.</li><li>The host starts the auction.</li><li>Each player has a 10-second bidding window.</li><li>Every valid bid resets the timer to 10 seconds.</li><li>The highest bidder wins when the timer reaches zero.</li><li>Manage your ₹120 Cr purse and build a balanced squad.</li><li>The host can end the auction to show final results.</li></ol><button className="primary full" onClick={onClose}>Got it</button></div></div> }

function Entry({mode,name,setName,teamId,setTeamId,roomCode,setRoomCode,onBack,onSubmit,error}){ return <div className="page-shell centered"><div className="entry-card"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Back</button><div className="entry-head"><span className="logo-chip">PU</span><div><div className="eyebrow">{mode==='create'?'NEW AUCTION ROOM':'JOIN AUCTION ROOM'}</div><h2>{mode==='create'?'Create your room':'Join your friends'}</h2></div></div><label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder="e.g. Sujith"/></label>{mode==='join'&&<label>Room code<input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="PU-7K4X9"/></label>}<label>Choose your team<div className="team-grid">{TEAMS.map(([id,n])=><button type="button" key={id} className={`team-select ${teamId===id?'selected':''}`} style={{'--team':teamColor[id]}} onClick={()=>setTeamId(id)}><span>{id}</span><small>{n}</small></button>)}</div></label>{error&&<div className="error-box"><X size={16}/>{error}</div>}<button className="primary full" onClick={onSubmit}>{mode==='create'?<><Gavel/> Create Auction</>:<><LogIn/> Join Room</>}</button><p className="hint">Your team cannot be selected by another player once you join.</p></div></div> }

function Lobby({room,userId,isHost,copyLink,copied,onStart,onBack}){ const taken=new Set(room.players.map(p=>p.teamId)); return <div className="page-shell lobby-page"><nav className="topbar"><Brand/><div className="room-pill">ROOM <b>{room.code}</b><button onClick={copyLink}>{copied?<Check size={15}/>:<Copy size={15}/>}</button></div><button className="icon-btn" onClick={onBack}><LogOut size={17}/> Leave</button></nav><main className="lobby"><section className="lobby-main"><div className="section-kicker"><span className="live-dot"/> PRIVATE AUCTION LOBBY</div><h1>Bring your squad.</h1><p>Share the invite, choose your IPL team, and wait for everyone to join.</p><div className="lobby-count"><strong>{room.players.length}</strong><span>/ 10 players joined</span><i>•</i><span>₹120 Cr per team</span></div><div className="players-grid">{room.players.map(p=><div className="player-lobby" key={p.id}><div className="avatar" style={{'--team':teamColor[p.teamId]}}>{p.name.slice(0,2).toUpperCase()}</div><div><strong>{p.name}{p.id===userId&&' (you)'}</strong><span style={{color:teamColor[p.teamId]}}>{p.teamId}</span></div>{p.isHost&&<span className="host-tag"><Crown size={13}/> HOST</span>}<span className={`connection ${p.connected?'online':'offline'}`}/></div>)}{Array.from({length:Math.max(0,10-room.players.length)}).map((_,i)=><div className="player-lobby empty" key={i}><div className="avatar muted">?</div><div><strong>Open slot</strong><span>Waiting for player</span></div></div>)}</div></section><aside className="lobby-side"><div className="side-card share-card"><div className="side-title">LIVE INVITE</div><div className="share-code">{room.code}</div><p>Send this link to players on the same Wi-Fi. They will land on the PADDLE UP home page and see this room ready to join.</p><button className="primary full" onClick={copyLink}>{copied?<><Check size={17}/> Link Copied</>:<><Copy size={17}/> Copy Live Invite Link</>}</button><div className="share-note">Room code <b>{room.code}</b> · {room.players.length}/10 joined</div></div><div className="side-card"><div className="side-title">TEAM STATUS</div><div className="available-teams">{TEAMS.map(([id,n])=><div key={id} className={taken.has(id)?'taken':''}><span className="team-dot" style={{background:teamColor[id]}}/>{id}<small>{taken.has(id)?'TAKEN':'AVAILABLE'}</small></div>)}</div></div>{isHost&&<button className="primary full start-btn" disabled={!room.players.length} onClick={onStart}><Gavel/> Start Auction <ChevronRight/></button>}</aside></main></div> }
function Brand(){return <div className="brand"><span className="brand-mark premium-logo"><span>PU</span></span><div><b>PADDLE UP</b><small>Build Your Squad. Rule the Auction.</small></div></div>}

function Attr({label,value}){
  const n=Number(value||0);
  return <div className="attr"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,n))}%`}}/></div><b>{n||'—'}</b></div>;
}

function HostControls({room}){
  return <div className="host-controls">
    <div className="host-label"><Crown size={14}/> HOST CONSOLE</div>
    <div className="host-buttons">
      {room.status==='LIVE' ? <button className="secondary" onClick={()=>socket.emit('host:pause')}><Pause size={14}/> Pause</button> : <button className="secondary" onClick={()=>socket.emit('host:resume')}><Play size={14}/> Resume</button>}
      <button className="secondary" onClick={()=>socket.emit('host:restart')}><RotateCcw size={14}/> Restart lot</button>
      <button className="secondary" onClick={()=>socket.emit('host:skip')}><ChevronRight size={14}/> Skip / settle</button>
    </div>
  </div>;
}

function Auction({room,userId,myTeam,isHost,remaining,sound,setSound,currentPlayer,myTeamData,toast}){
 const a=room.currentAuction;
 const timer=Math.max(0,remaining);
 const next=a?Number((a.currentBid + (a.currentBid<5?.25:a.currentBid<10?.5:a.currentBid<20?1:2)).toFixed(2)):0;
 const canBid=room.status==='LIVE'&&a?.status==='LIVE'&&myTeam&&a?.highestTeam!==myTeam&&myTeamData?.purse>=next&&timer>0;
 const [tab,setTab]=useState('activity');
 const [confirm,setConfirm]=useState(false);
 const [powerAmount,setPowerAmount]=useState('');
 const [showAllUpcoming,setShowAllUpcoming]=useState(false);
 const selectedTeamIds=useMemo(()=>room.players.map(p=>p.teamId).filter(Boolean),[room.players]);
 const selectedTeams=selectedTeamIds.map(id=>[id,room.teams[id]]).filter(([,t])=>t);
 const playerMap=useMemo(()=>Object.fromEntries((room.playerPool||[]).map(p=>[p.id,p])),[room.playerPool]);
 const upcomingAll=(room.pool||[]).slice(room.auctionIndex+1).map(id=>playerMap[id]).filter(Boolean);
 const upcoming=upcomingAll.slice(0,6);
 const myTeamPlayers=myTeamData?.players||[];
 const otherTeams=selectedTeams.filter(([id])=>id!==myTeam);
 const powerBidsLeft=Number(myTeamData?.powerBidsRemaining ?? 2);
 const powerValue=Number(powerAmount);
 const canPowerBid=canBid && powerBidsLeft>0 && Number.isFinite(powerValue) && powerValue>=next && powerValue<=Number(myTeamData?.purse||0);
 const bid=()=>{ if(canBid){socket.emit('auction:bid',{teamId:myTeam}); beep(sound,880,.05)} };
 const powerBid=()=>{ if(canPowerBid){socket.emit('auction:power-bid',{teamId:myTeam,amount:powerValue}); beep(sound,1040,.07); setPowerAmount('');} };
 return <div className="page-shell auction-page">
  <nav className="topbar auction-top"><Brand/><div className="auction-meta"><span className={`status ${room.status.toLowerCase()}`}>{room.status==='LIVE'?'● LIVE':room.status}</span><span className="room-pill">ROOM {room.code}</span><span className="online"><Users size={15}/>{room.players.filter(p=>p.connected).length} online</span><span className="pool-count">{Math.max(0,room.pool?.length-(room.auctionIndex+1))} UPCOMING / {room.pool?.length||0} LOTS</span></div><div className="top-actions"><button className="icon-btn compact sound-toggle" onClick={()=>setSound(v=>!v)}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{sound?'SOUND ON':'SOUND OFF'}</span></button>{isHost&&<button className="danger-btn" onClick={()=>setConfirm(true)}>End Auction</button>}</div></nav>
  <main className="auction-grid">
   <section className="auction-player">
    <div className="player-meta"><span className="pill">{currentPlayer?.auctionCategory || room.currentAuction?.category || (currentPlayer?.custom?'CUSTOM / FRIEND PLAYER':currentPlayer?.role?.toUpperCase())}</span><span>Lot #{room.auctionIndex+1}</span><span className="category-progress">SET {(currentPlayer?.auctionCategoryIndex ?? room.currentAuction?.categoryIndex ?? 0)+1} / {room.auctionCategories?.length || 11}</span></div>
    <div className="player-card"><div className={`photo-wrap ${toast?.type==='SOLD'?'result-active-sold':toast?.type==='UNSOLD'?'result-active-unsold':''}`}><img src={currentPlayer?.photo} alt=""/><div className="player-result-mark" aria-live="polite">{toast?.type==='SOLD'&&<motion.div className="result-stamp sold" initial={{scale:.45,rotate:-10,opacity:0}} animate={{scale:1,rotate:0,opacity:1}} transition={{type:'spring',stiffness:420,damping:18}}><Check size={30}/><strong>SOLD</strong><span>{toast.detail}</span></motion.div>}{toast?.type==='UNSOLD'&&<motion.div className="result-stamp unsold" initial={{scale:.45,rotate:10,opacity:0}} animate={{scale:1,rotate:0,opacity:1}} transition={{type:'spring',stiffness:420,damping:18}}><X size={30}/><strong>UNSOLD</strong><span>No successful bid</span></motion.div>}</div><div className="rating"><small>OVR</small><b>{currentPlayer?.rating}</b></div></div><div className="player-info"><h1>{currentPlayer?.name || 'Auction complete'}</h1><div className="player-role">{currentPlayer?.displayRole || currentPlayer?.role} <span>•</span> {currentPlayer?.nationality}</div><div className="attribute-grid"><Attr label="Batting" value={currentPlayer?.batting}/><Attr label="Bowling" value={currentPlayer?.bowling}/><Attr label="Fielding" value={currentPlayer?.fielding}/></div><div className="history"><span>Previous IPL teams</span><div>{(currentPlayer?.previousTeams||[]).map(t=><b key={t}>{t}</b>)}</div></div></div></div>
    <div className="auction-battle"><div className="bid-stat"><small>BASE PRICE</small><strong>{money(a?.basePrice)}</strong></div><div className="bid-stat current"><small>CURRENT BID</small><strong>{money(a?.currentBid)}</strong><span>{a?.highestTeam?`Leading: ${a.highestTeam}`:'No bids yet'}</span></div><div className="bid-stat"><small>NEXT BID</small><strong>{money(next)}</strong><span>Increment {money(next-(a?.currentBid||0))}</span></div></div>
    <div className={`timer-panel-v2 ${timer<=3?'danger':''}`}><div className="timer-orbit"><div className="timer-glow"/><div className="timer-core"><small>TIME</small><strong>{Math.ceil(timer).toString().padStart(2,'0')}</strong><span>SEC</span></div><svg className="timer-svg" viewBox="0 0 120 120" aria-hidden="true"><circle className="timer-track" cx="60" cy="60" r="52"/><circle className="timer-progress" cx="60" cy="60" r="52" style={{strokeDashoffset: `${326.73 - (326.73*Math.min(100,timer/room.settings.timerSeconds*100)/100)}`}}/></svg></div><div className="timer-copy"><div className="timer-kicker"><span className="pulse-dot"/>{timer<=3?'FINAL CALL':'BIDDING LIVE'}</div><strong>{a?.highestTeam?`${a.highestTeam} is leading`:'Opening bid'}</strong><span>10 seconds after every valid bid · same team must wait for another bid</span></div></div>
    <button className="bid-now" disabled={!canBid} onClick={bid}><Gavel/><span>{canBid?`BID ${money(next)}`:room.status==='PAUSED'?'AUCTION PAUSED':a?.highestTeam===myTeam?'WAIT FOR ANOTHER TEAM':myTeamData?.purse<next?'INSUFFICIENT FUNDS':'BIDDING CLOSED'}</span></button>
    <div className="power-bid-panel">
      <div className="power-bid-copy"><div><Zap size={15}/><strong>POWER BID</strong></div><span>{powerBidsLeft} of 2 remaining · jump straight to your chosen amount</span></div>
      <div className="power-bid-actions"><label>₹<input type="number" min={next} step="0.25" value={powerAmount} onChange={e=>setPowerAmount(e.target.value)} placeholder={next.toFixed(2)} disabled={!canBid||powerBidsLeft<=0}/><small>Cr</small></label><button className="power-bid-btn" disabled={!canPowerBid} onClick={powerBid}><Zap size={14}/>{powerBidsLeft?`POWER BID${powerAmount?` ${money(powerValue)}`:''}`:'USED UP'}</button></div>
    </div>
    {isHost&&<HostControls room={room} confirm={()=>setConfirm(true)}/>} 
   </section>
   <aside className="auction-side">
    <div className="side-card live-bids">
     <div className="auction-pool-banner"><div><small>AUCTION POOL</small><strong>{room.pool?.length||0} players</strong></div><div className="pool-banner-right"><span>{Math.max(0,(room.pool?.length||0)-(room.auctionIndex+1))} upcoming</span><button className="view-all-btn" onClick={()=>setShowAllUpcoming(true)}>View all</button></div></div>
     <div className="tabs squad-tabs"><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Live Bids</button><button className={tab==='my'?'active':''} onClick={()=>setTab('my')}>My Squad</button><button className={tab==='others'?'active':''} onClick={()=>setTab('others')}>Other Squads</button><button className={tab==='upcoming'?'active':''} onClick={()=>setTab('upcoming')}>Upcoming</button><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}>AI Review</button></div>
     {tab==='activity'&&<div className="bid-list">{(a?.bids||[]).slice().reverse().map((b,i)=><div className="bid-row" key={i}><span className="team-badge" style={{'--team':teamColor[b.teamId]}}>{b.teamId}</span><div><strong>{money(b.amount)}</strong><small>{b.bidderName}</small></div><span className="bid-time">LIVE</span></div>)}{!(a?.bids||[]).length&&<EmptyState text="No bids yet. Be the first."/>}</div>}
     {tab==='my'&&<SquadPanel teamId={myTeam} team={myTeamData} playerMap={playerMap} mine/>}
     {tab==='others'&&<div className="squads-mini">{otherTeams.length?otherTeams.map(([id,t])=><SquadPanel key={id} teamId={id} team={t} playerMap={playerMap}/>):<EmptyState text="No other teams have joined yet."/>}</div>}
     {tab==='upcoming'&&<UpcomingPlayers players={upcoming} start={room.auctionIndex+2}/>}
     {tab==='review'&&<LiveReview teamId={myTeam} analysis={room.teamAnalysis?.[myTeam]} team={myTeamData}/>} 
    </div>
    <div className="side-card purse-card"><div className="side-title">Selected team purses <span>{selectedTeams.length} teams</span></div>{selectedTeams.map(([id,t])=><div className={`purse-row ${id===myTeam?'my-team-row':''}`} key={id}><span className="team-dot" style={{background:teamColor[id]}}/><b>{id}</b><span>{money(t.purse)}</span><small>{t.players.length} players</small></div>)}</div>
   </aside>
  </main><AnimatePresence>{toast&&<AuctionToast toast={toast}/>}</AnimatePresence> {showAllUpcoming&&<UpcomingModal players={upcomingAll} start={room.auctionIndex+2} onClose={()=>setShowAllUpcoming(false)}/>} {confirm&&<Confirm onCancel={()=>setConfirm(false)} onConfirm={()=>socket.emit('host:end')}/>}</div>
}
function AuctionToast({toast}){ const data=typeof toast==='string'?{type:'INFO',title:'NOTICE',text:toast,detail:''}:toast; const sold=data.type==='SOLD'; const unsold=data.type==='UNSOLD'; return <motion.div className={`auction-toast ${sold?'sold':unsold?'unsold':''}`} initial={{opacity:0,x:35,y:-8}} animate={{opacity:1,x:0,y:0}} exit={{opacity:0,x:35}} transition={{type:'spring',stiffness:360,damping:28}}><div className="auction-toast-icon">{sold?'✓':unsold?'—':'•'}</div><div className="auction-toast-copy"><small>{data.title}</small><strong>{data.text}</strong>{data.detail&&<span>{data.detail}</span>}</div><div className="auction-toast-line"/></motion.div>}
function SquadPanel({teamId,team,playerMap,mine=false}){ if(!team) return <EmptyState text="Your team is not available."/>; return <div className={`squad-panel ${mine?'my-squad-panel':''}`}><div className="squad-panel-head"><div><span className="team-crest-small" style={{'--team':teamColor[teamId]}}>{teamId}</span><div><strong>{mine?'MY SQUAD':team.name}</strong><small>{team.players.length} players · {money(team.purse)} left</small></div></div>{mine&&<span className="you-tag">YOU</span>}</div><div className="squad-names big-names">{team.players.length?team.players.map(x=><span key={x.playerId}>{playerMap[x.playerId]?.name||'Player'}</span>):<em>No players bought yet</em>}</div></div>}
function UpcomingModal({players,start,onClose}){return <div className="modal-backdrop upcoming-modal-backdrop" onClick={onClose}><motion.div className="upcoming-modal" initial={{opacity:0,y:20,scale:.98}} animate={{opacity:1,y:0,scale:1}} onClick={e=>e.stopPropagation()}><div className="upcoming-modal-head"><div><small>FULL AUCTION QUEUE</small><h2>Upcoming Players</h2><span>{players.length} players remaining</span></div><button className="modal-close" onClick={onClose}><X size={18}/></button></div><div className="upcoming-full-list">{players.length?players.map((p,i)=><div className="upcoming-player full" key={p.id}><span className="lot-number">#{start+i}</span><div className="upcoming-avatar">{p.name.slice(0,2).toUpperCase()}</div><div className="upcoming-full-copy"><strong>{p.name}</strong><small>{p.auctionCategory || p.role} · {p.displayRole || p.role} · Base {money(p.basePrice)}</small></div><b>{p.rating||'—'}</b></div>):<EmptyState text="No more players in the auction pool."/>}</div></motion.div></div>}
function UpcomingPlayers({players,start}){return <div className="upcoming-list">{players.length?players.map((p,i)=><div className="upcoming-player" key={p.id}><span className="lot-number">#{start+i}</span><div className="upcoming-avatar">{p.name.slice(0,2).toUpperCase()}</div><div><strong>{p.name}</strong><small>{p.auctionCategory || p.role} · Base {money(p.basePrice)}</small></div></div>):<EmptyState text="No more players in the auction pool."/>}</div>}
function LiveReview({teamId,analysis,team}){if(!analysis)return <EmptyState text="Buy a player to activate the live squad review."/>;return <div className="live-review"><div className="review-head"><div><div className="eyebrow">LIVE AI REVIEW</div><h3>{teamId} SQUAD</h3></div><span className="review-score">{analysis.squadRating}<small>/99</small></span></div><p className="review-headline">{analysis.headline}</p><p className="review-insight">{analysis.insight}</p><div className="review-metrics"><Score label="Batting" value={analysis.batting}/><Score label="Bowling" value={analysis.bowling}/><Score label="Keeping" value={analysis.keeping}/><Score label="Balance" value={analysis.squadBalance}/></div><div className="review-columns"><div><b>Strengths</b>{analysis.strengths.map((x,i)=><span key={i}><Check/> {x}</span>)}</div><div><b>Weaknesses</b>{analysis.weaknesses.map((x,i)=><span key={i}><span className="warn">!</span> {x}</span>)}</div></div><div className="review-foot">Updates automatically after every player is sold.</div></div>}
function EmptyState({text}){return <div className="empty-state"><Gavel size={20}/><span>{text}</span></div>}
function Confirm({onCancel,onConfirm}){return <div className="modal-backdrop"><div className="confirm-card"><div className="modal-icon"><LogOut/></div><h2>End the auction?</h2><p>Everyone will move to the final results screen. This cannot be undone.</p><div className="modal-actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="danger-btn big-danger" onClick={onConfirm}>End Auction</button></div></div></div>}

function Results({room,onAgain}){const playerMap=Object.fromEntries((room.playerPool||[]).map(p=>[p.id,p])); const ids=room.selectedTeamIds?.length?room.selectedTeamIds:[...new Set(room.players.map(p=>p.teamId))]; const stats=ids.map(id=>{const entry=TEAMS.find(([x])=>x===id); const name=entry?.[1]||room.teams[id]?.name||id; const t=room.teams[id]; const s=room.teamAnalysis?.[id]||calcStats(t,playerMap);return {...t,id,name,stats:s}}).sort((a,b)=>b.stats.rating-a.stats.rating); const sold=room.history.filter(x=>x.status==='SOLD'); const unsold=room.history.filter(x=>x.status==='UNSOLD'); const total=sold.reduce((s,x)=>s+x.price,0); const expensive=sold.slice().sort((a,b)=>b.price-a.price)[0]; return <div className="page-shell results-page"><nav className="topbar"><Brand/><div className="status ended">● AUCTION ENDED</div><button className="primary compact" onClick={onAgain}>New Room</button></nav><main className="results"><div className="results-hero"><div className="trophy">🏆</div><div><div className="eyebrow">PADDLE UP</div><h1>AUCTION COMPLETE</h1><p>Every bid is now part of your squad story.</p></div></div><div className="result-stats"><Stat label="Players sold" value={sold.length}/><Stat label="Players unsold" value={unsold.length}/><Stat label="Total spent" value={money(total)}/><Stat label="Biggest bid" value={expensive?money(expensive.price):'—'} sub={expensive?.playerName}/></div><section className="comparison"><div className="section-heading"><div><div className="eyebrow">SQUAD ANALYSIS</div><h2>Every team. Every number.</h2></div><div className="explain"><BarChart3 size={16}/> Ratings combine player attributes, role depth, squad balance and remaining purse.</div></div><div className="team-results">{stats.map((x,i)=><TeamResult key={x.id} team={x} rank={i+1} playerMap={playerMap}/>)}</div></section><section className="history-section"><div className="section-heading"><div><div className="eyebrow">AUCTION HISTORY</div><h2>What happened in the room</h2></div></div><div className="history-table"><div className="table-head"><span>Player</span><span>Team</span><span>Price</span><span>Status</span></div>{room.history.slice().reverse().map((h,i)=><div className="table-row" key={i}><span>{h.playerName}</span><b>{h.teamId||'—'}</b><span>{h.status==='SOLD'?money(h.price):'—'}</span><em className={h.status.toLowerCase()}>{h.status}</em></div>)}</div></section><div className="results-actions"><button className="primary" onClick={onAgain}><Sparkles/> Play Again</button><button className="secondary" onClick={()=>window.print()}>Print Results</button></div></main></div>}
function calcStats(t,map){const ps=t.players.map(x=>map[x.playerId]).filter(Boolean);const n=ps.length||1;const avg=k=>ps.reduce((s,p)=>s+(p[k]||0),0)/n;const c=r=>ps.filter(p=>p.role===r).length;const batting=Math.min(100,Math.round(avg('batting')*.9+c('Batsman')*2));const bowling=Math.min(100,Math.round(avg('bowling')*.9+c('Bowler')*2));const all=Math.min(100,Math.round(avg('rating')*.5+avg('fielding')*.2+c('All-Rounder')*7));const keep=c('Wicket-Keeper')?Math.min(100,Math.round(avg('fielding')*.55+45+c('Wicket-Keeper')*5)):20;const balance=Math.min(100,Math.round((batting+bowling+all+keep)/4+Math.min(8,ps.length)));const rating=Math.min(99,Math.round(avg('rating')*.72+balance*.18+Math.min(ps.length,11)));const strengths=[];const weaknesses=[];if(batting>=85)strengths.push('Strong batting depth');if(bowling>=85)strengths.push('Experienced bowling attack');if(c('All-Rounder')>=2)strengths.push('Good all-rounder coverage');if(c('Wicket-Keeper')>=2)strengths.push('Strong keeping cover');if(!c('Wicket-Keeper'))weaknesses.push('No wicket-keeper');if(c('Bowler')<3)weaknesses.push('Limited bowling depth');if(c('Batsman')<3)weaknesses.push('Limited batting depth');if(c('Wicket-Keeper')===1)weaknesses.push('Limited backup wicket-keeper');if(!strengths.length)strengths.push('Room to build across roles');return {rating,batting,bowling,all,keep,balance,players:ps.length,strengths,weaknesses}}
function TeamResult({team,rank,playerMap}){return <div className="team-result"><div className="team-result-head"><div className="rank">#{rank}</div><div className="team-crest" style={{'--team':teamColor[team.id]}}>{team.id}</div><div className="team-name"><strong>{team.name}</strong><span>{team.stats.players} players · {money(team.purse)} remaining</span></div><div className="overall"><small>Squad rating</small><b>{team.stats.rating}</b><span>/ 99</span></div></div><div className="bars"><Score label="Batting" value={team.stats.batting}/><Score label="Bowling" value={team.stats.bowling}/><Score label="All-rounders" value={team.stats.all}/><Score label="Keeping" value={team.stats.keep}/><Score label="Balance" value={team.stats.balance}/></div><div className="ai-review-box"><div><Sparkles size={15}/><b>AI SQUAD REVIEW</b></div><strong>{team.stats.headline}</strong><p>{team.stats.insight}</p></div><div className="strengths"><div><b>Strengths</b>{team.stats.strengths.map(s=><span key={s}><Check/> {s}</span>)}</div><div><b>Areas to improve</b>{team.stats.weaknesses.map(s=><span key={s}><span className="warn">!</span> {s}</span>)}</div></div><div className="result-players">{team.players.map(x=>{const p=playerMap[x.playerId];return <span key={x.playerId}>{p?.name} <b>{money(x.price)}</b></span>})}</div></div>}
function Score({label,value}){return <div className="score"><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{value}</b></div>}
function Stat({label,value,sub}){return <div className="result-stat"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
let paddleAudio=null;
function getAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!paddleAudio)paddleAudio=new C();if(paddleAudio.state==='suspended')paddleAudio.resume();return paddleAudio}catch{return null}}
function tone(c,freq,start,duration,gain=.045,type='sine',slide=0){const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(40,freq+slide),start+duration);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(gain,start+.012);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g);g.connect(c.destination);o.start(start);o.stop(start+duration+.02)}
function auctionSound(kind){const c=getAudio();if(!c)return;const n=c.currentTime+.01;if(kind==='bid'){tone(c,540,n,.08,.035,'square',180);tone(c,820,n+.06,.1,.025,'sine',-100)}else if(kind==='sold'){tone(c,420,n,.09,.035,'triangle',90);tone(c,620,n+.09,.11,.045,'triangle',120);tone(c,900,n+.19,.18,.055,'triangle',0)}else if(kind==='unsold'){tone(c,320,n,.16,.035,'sine',-80);tone(c,220,n+.12,.2,.025,'sine',-40)}else if(kind==='countdown'){tone(c,760,n,.09,.03,'square',0)}}
function beep(sound,freq,duration){if(!sound)return;const c=getAudio();if(!c)return;tone(c,freq,c.currentTime+.01,duration,.025,'square',80)}

export default App;
